apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: web
  labels:
    app: myapp
spec:
  containers:
  - name: nginx-container
    image: nginx
    command: ['nginx']
    args: ['-g', 'daemon off;', '-q']
    ports:
    - containerPort: 80