apiVersion: v1
kind: Service
metadata:
  name: pizza-service
  namespace: pizza
spec:
  selector:
    app: pizza
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30080
